///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：$(CodeGenericType)
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [Icon("")]
    [DisplayName("SceneManager_LoadScene")]
    [Category("Unity/SceneManager")]
    [AddComponentMenu("LoadScene(String, LoadSceneMode)")]
    public sealed class SceneManager_LoadScene_String_LoadSceneMode : BTActionNode
    {
        [Space]
        public Megumin.Binding.RefVar_String sceneName;
        public Megumin.Binding.RefVar<UnityEngine.SceneManagement.LoadSceneMode> mode;

        protected override Status OnTick(BTNode from, object options = null)
        {
            UnityEngine.SceneManagement.SceneManager.LoadScene(sceneName, mode);
            return Status.Succeeded;
        }
    }
}




