///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：$(CodeGenericType)
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [Icon("")]
    [DisplayName("SceneManager_SetActiveScene")]
    [Category("Unity/SceneManager")]
    [AddComponentMenu("SetActiveScene(Scene)")]
    public sealed class SceneManager_SetActiveScene_Scene : ConditionDecorator
    {
        [Space]
        public Megumin.Binding.RefVar<UnityEngine.SceneManagement.Scene> scene;

        public Megumin.Binding.RefVar_Bool Result;

        public override bool CheckCondition(object options = null)
        {
            var result = UnityEngine.SceneManagement.SceneManager.SetActiveScene(scene);

            if (Result != null)
            {
                Result.Value = result;
            }

            return result;
        }
    }
}




