///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：$(CodeGenericType)
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

using System;
using System.Collections.Generic;
using Megumin.Binding;
using UnityEngine;

namespace Megumin.GameFramework.AI
{
    public partial class VariableCreator
    {
        /// <summary>
        /// 用户可以在这里添加参数类型到菜单。
        /// </summary>
        public static List<VariableCreator> AllCreator = new()
        {
            new VariableCreator_bool(),
            new VariableCreator_int(),
            new VariableCreator_long(),
            new VariableCreator_string(),
            new VariableCreator_float(),
            new VariableCreator_double(),
            new Separator(),
            new VariableCreator_Vector2(),
            new VariableCreator_Vector2Int(),
            new VariableCreator_Vector3(),
            new VariableCreator_Vector3Int(),
            new VariableCreator_Vector4(),
            new VariableCreator_Rect(),
            new VariableCreator_RectInt(),
            new VariableCreator_Bounds(),
            new VariableCreator_BoundsInt(),
            new Separator(),
            new VariableCreator_GameObject(),
            new VariableCreator_Transform(),
            new VariableCreator_ScriptableObject(),
            new VariableCreator_Trigger(),
            new VariableCreator_Color(),
            new VariableCreator_Gradient(),
            new VariableCreator_Texture2D(),
            new VariableCreator_RenderTexture(),
            new VariableCreator_AnimationCurve(),
            new VariableCreator_Mesh(),
            new VariableCreator_SkinnedMeshRenderer(),
            new VariableCreator_Material(),
        };
    }

    public class RefVar_bool : RefVar<bool> { }

    public class VariableCreator_bool : VariableCreator
    {
        public override string Name { get; set; } = "bool";

        public override IRefable Create()
        {
            return new RefVar_bool() { RefName = "Bool" };
        }
    }

    public class RefVar_int : RefVar<int> { }

    public class VariableCreator_int : VariableCreator
    {
        public override string Name { get; set; } = "int";

        public override IRefable Create()
        {
            return new RefVar_int() { RefName = "Int" };
        }
    }

    public class RefVar_long : RefVar<long> { }

    public class VariableCreator_long : VariableCreator
    {
        public override string Name { get; set; } = "long";

        public override IRefable Create()
        {
            return new RefVar_long() { RefName = "Long" };
        }
    }

    public class RefVar_string : RefVar<string> { }

    public class VariableCreator_string : VariableCreator
    {
        public override string Name { get; set; } = "string";

        public override IRefable Create()
        {
            return new RefVar_string() { RefName = "String" };
        }
    }

    public class RefVar_float : RefVar<float> { }

    public class VariableCreator_float : VariableCreator
    {
        public override string Name { get; set; } = "float";

        public override IRefable Create()
        {
            return new RefVar_float() { RefName = "Float" };
        }
    }

    public class RefVar_double : RefVar<double> { }

    public class VariableCreator_double : VariableCreator
    {
        public override string Name { get; set; } = "double";

        public override IRefable Create()
        {
            return new RefVar_double() { RefName = "Double" };
        }
    }

    public class RefVar_Vector2 : RefVar<Vector2> { }

    public class VariableCreator_Vector2 : VariableCreator
    {
        public override string Name { get; set; } = "Vector2";

        public override IRefable Create()
        {
            return new RefVar_Vector2() { RefName = "Vector2" };
        }
    }

    public class RefVar_Vector2Int : RefVar<Vector2Int> { }

    public class VariableCreator_Vector2Int : VariableCreator
    {
        public override string Name { get; set; } = "Vector2Int";

        public override IRefable Create()
        {
            return new RefVar_Vector2Int() { RefName = "Vector2Int" };
        }
    }

    public class RefVar_Vector3 : RefVar<Vector3> { }

    public class VariableCreator_Vector3 : VariableCreator
    {
        public override string Name { get; set; } = "Vector3";

        public override IRefable Create()
        {
            return new RefVar_Vector3() { RefName = "Vector3" };
        }
    }

    public class RefVar_Vector3Int : RefVar<Vector3Int> { }

    public class VariableCreator_Vector3Int : VariableCreator
    {
        public override string Name { get; set; } = "Vector3Int";

        public override IRefable Create()
        {
            return new RefVar_Vector3Int() { RefName = "Vector3Int" };
        }
    }

    public class RefVar_Vector4 : RefVar<Vector4> { }

    public class VariableCreator_Vector4 : VariableCreator
    {
        public override string Name { get; set; } = "Vector4";

        public override IRefable Create()
        {
            return new RefVar_Vector4() { RefName = "Vector4" };
        }
    }

    public class RefVar_Rect : RefVar<Rect> { }

    public class VariableCreator_Rect : VariableCreator
    {
        public override string Name { get; set; } = "Rect";

        public override IRefable Create()
        {
            return new RefVar_Rect() { RefName = "Rect" };
        }
    }

    public class RefVar_RectInt : RefVar<RectInt> { }

    public class VariableCreator_RectInt : VariableCreator
    {
        public override string Name { get; set; } = "RectInt";

        public override IRefable Create()
        {
            return new RefVar_RectInt() { RefName = "RectInt" };
        }
    }

    public class RefVar_Bounds : RefVar<Bounds> { }

    public class VariableCreator_Bounds : VariableCreator
    {
        public override string Name { get; set; } = "Bounds";

        public override IRefable Create()
        {
            return new RefVar_Bounds() { RefName = "Bounds" };
        }
    }

    public class RefVar_BoundsInt : RefVar<BoundsInt> { }

    public class VariableCreator_BoundsInt : VariableCreator
    {
        public override string Name { get; set; } = "BoundsInt";

        public override IRefable Create()
        {
            return new RefVar_BoundsInt() { RefName = "BoundsInt" };
        }
    }

    public class RefVar_GameObject : RefVar<GameObject> { }

    public class VariableCreator_GameObject : VariableCreator
    {
        public override string Name { get; set; } = "GameObject";

        public override IRefable Create()
        {
            return new RefVar_GameObject() { RefName = "GameObject" };
        }
    }

    public class RefVar_Transform : RefVar<Transform> { }

    public class VariableCreator_Transform : VariableCreator
    {
        public override string Name { get; set; } = "Transform";

        public override IRefable Create()
        {
            return new RefVar_Transform() { RefName = "Transform" };
        }
    }

    public class RefVar_ScriptableObject : RefVar<ScriptableObject> { }

    public class VariableCreator_ScriptableObject : VariableCreator
    {
        public override string Name { get; set; } = "ScriptableObject";

        public override IRefable Create()
        {
            return new RefVar_ScriptableObject() { RefName = "ScriptableObject" };
        }
    }

    public class RefVar_Trigger : RefVar<Trigger> { }

    public class VariableCreator_Trigger : VariableCreator
    {
        public override string Name { get; set; } = "Trigger";

        public override IRefable Create()
        {
            return new RefVar_Trigger() { RefName = "Trigger" };
        }
    }

    public class RefVar_Color : RefVar<Color> { }

    public class VariableCreator_Color : VariableCreator
    {
        public override string Name { get; set; } = "Color";

        public override IRefable Create()
        {
            return new RefVar_Color() { RefName = "Color" };
        }
    }

    public class RefVar_Gradient : RefVar<Gradient> { }

    public class VariableCreator_Gradient : VariableCreator
    {
        public override string Name { get; set; } = "Gradient";

        public override IRefable Create()
        {
            return new RefVar_Gradient() { RefName = "Gradient" };
        }
    }

    public class RefVar_Texture2D : RefVar<Texture2D> { }

    public class VariableCreator_Texture2D : VariableCreator
    {
        public override string Name { get; set; } = "Texture2D";

        public override IRefable Create()
        {
            return new RefVar_Texture2D() { RefName = "Texture2D" };
        }
    }

    public class RefVar_RenderTexture : RefVar<RenderTexture> { }

    public class VariableCreator_RenderTexture : VariableCreator
    {
        public override string Name { get; set; } = "RenderTexture";

        public override IRefable Create()
        {
            return new RefVar_RenderTexture() { RefName = "RenderTexture" };
        }
    }

    public class RefVar_AnimationCurve : RefVar<AnimationCurve> { }

    public class VariableCreator_AnimationCurve : VariableCreator
    {
        public override string Name { get; set; } = "AnimationCurve";

        public override IRefable Create()
        {
            return new RefVar_AnimationCurve() { RefName = "AnimationCurve" };
        }
    }

    public class RefVar_Mesh : RefVar<Mesh> { }

    public class VariableCreator_Mesh : VariableCreator
    {
        public override string Name { get; set; } = "Mesh";

        public override IRefable Create()
        {
            return new RefVar_Mesh() { RefName = "Mesh" };
        }
    }

    public class RefVar_SkinnedMeshRenderer : RefVar<SkinnedMeshRenderer> { }

    public class VariableCreator_SkinnedMeshRenderer : VariableCreator
    {
        public override string Name { get; set; } = "SkinnedMeshRenderer";

        public override IRefable Create()
        {
            return new RefVar_SkinnedMeshRenderer() { RefName = "SkinnedMeshRenderer" };
        }
    }

    public class RefVar_Material : RefVar<Material> { }

    public class VariableCreator_Material : VariableCreator
    {
        public override string Name { get; set; } = "Material";

        public override IRefable Create()
        {
            return new RefVar_Material() { RefName = "Material" };
        }
    }
}
