///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：$(CodeGenericType)
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [Icon("AudioSource Icon")]
    [DisplayName("AudioSource_SetAmbisonicDecoderFloat")]
    [Category("Unity/AudioSource")]
    [AddComponentMenu("SetAmbisonicDecoderFloat(Int32, Single)")]
    public sealed class AudioSource_SetAmbisonicDecoderFloat_Int32_Single : ConditionDecorator<UnityEngine.AudioSource>
    {
        [Space]
        public Megumin.Binding.RefVar_Int index;
        public Megumin.Binding.RefVar_Float value;

        public Megumin.Binding.RefVar_Bool Result;

        public override bool CheckCondition(object options = null)
        {
            var result = ((UnityEngine.AudioSource)MyAgent).SetAmbisonicDecoderFloat(index, value);

            if (Result != null)
            {
                Result.Value = result;
            }

            return result;
        }
    }
}




