///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：$(CodeGenericType)
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [Icon("")]
    [DisplayName("Vector2Int_Distance")]
    [Category("Unity/Vector2Int")]
    [AddComponentMenu("Distance(Vector2Int, Vector2Int)")]
    public sealed class Vector2Int_Distance_Vector2Int_Vector2Int : BTActionNode
    {
        [Space]
        public Megumin.Binding.RefVar_Vector2Int a;
        public Megumin.Binding.RefVar_Vector2Int b;

        public Megumin.Binding.RefVar_Float Result;

        protected override Status OnTick(BTNode from, object options = null)
        {
            var result = UnityEngine.Vector2Int.Distance(a, b);

            if (Result != null)
            {
                Result.Value = result;
            }

            return Status.Succeeded;
        }
    }
}




