///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：$(CodeGenericType)
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [Icon("")]
    [DisplayName("Vector2_Max")]
    [Category("Unity/Vector2")]
    [AddComponentMenu("Max(Vector2, Vector2)")]
    public sealed class Vector2_Max_Vector2_Vector2 : BTActionNode
    {
        [Space]
        public Megumin.Binding.RefVar_Vector2 lhs;
        public Megumin.Binding.RefVar_Vector2 rhs;

        public Megumin.Binding.RefVar_Vector2 Result;

        protected override Status OnTick(BTNode from, object options = null)
        {
            var result = UnityEngine.Vector2.Max(lhs, rhs);

            if (Result != null)
            {
                Result.Value = result;
            }

            return Status.Succeeded;
        }
    }
}




