///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：$(CodeGenericType)
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [Icon("")]
    [DisplayName("Quaternion_RotateTowards")]
    [Category("Unity/Quaternion")]
    [AddComponentMenu("RotateTowards(Quaternion, Quaternion, Single)")]
    public sealed class Quaternion_RotateTowards_Quaternion_Quaternion_Single : BTActionNode
    {
        [Space]
        public Megumin.Binding.RefVar<UnityEngine.Quaternion> from;
        public Megumin.Binding.RefVar<UnityEngine.Quaternion> to;
        public Megumin.Binding.RefVar_Float maxDegreesDelta;

        public Megumin.Binding.RefVar<UnityEngine.Quaternion> Result;

        protected override Status OnTick(BTNode from1, object options = null)
        {
            var result = UnityEngine.Quaternion.RotateTowards(from, to, maxDegreesDelta);

            if (Result != null)
            {
                Result.Value = result;
            }

            return Status.Succeeded;
        }
    }
}




