///********************************************************************************************************************************
///The code on this page is generated by the code generator, do not manually modify.
///CodeGenerator: Megumin.CSCodeGenerator.  Version: 1.0.1
///CodeGenericBy: Megumin.AI.BehaviorTree.Editor.NodeGenerator
///CodeGenericSourceFilePath: Packages/com.megumin.ai/Editor/BehaviorTree/Generator/InputSystem.asset
///********************************************************************************************************************************

#if ENABLE_INPUT_SYSTEM

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.AI.BehaviorTree
{
    [DisplayName("InputSystem_FindControls")]
    [Category("UnityEngine/InputSystem")]
    [AddComponentMenu("FindControls(String)")]
    public sealed class InputSystem_FindControls_String_Node : BTActionNode
    {
        [Space]
        public Megumin.Binding.RefVar_String path;

        [Space]
        public Megumin.Binding.RefVar<UnityEngine.InputSystem.InputControlList<UnityEngine.InputSystem.InputControl>> SaveValueTo;

        protected override Status OnTick(BTNode from, object options = null)
        {
            var result = UnityEngine.InputSystem.InputSystem.FindControls(path);

            if (SaveValueTo != null)
            {
                SaveValueTo.Value = result;
            }

            return Status.Succeeded;
        }
    }
}

#endif




