///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：$(CodeGenericType)
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

#if ENABLE_INPUT_SYSTEM

using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [Icon("")]
    [DisplayName("InputSystem_FindControls")]
    [Category("Unity/InputSystem")]
    [AddComponentMenu("FindControls(String)")]
    public sealed class InputSystem_FindControls_String : BTActionNode
    {
        [Space]
        public Megumin.Binding.RefVar_String path;

        public Megumin.Binding.RefVar<UnityEngine.InputSystem.InputControlList<UnityEngine.InputSystem.InputControl>> Result;

        protected override Status OnTick(BTNode from, object options = null)
        {
            var result = UnityEngine.InputSystem.InputSystem.FindControls(path);

            if (Result != null)
            {
                Result.Value = result;
            }

            return Status.Succeeded;
        }
    }
}

#endif




