///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：$(CodeGenericType)
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [Icon("Transform Icon")]
    [DisplayName("Transform_SetAsLastSibling")]
    [Category("Unity/Transform")]
    [AddComponentMenu("SetAsLastSibling")]
    public sealed class Transform_SetAsLastSibling : BTActionNode<UnityEngine.Transform>
    {

        protected override Status OnTick(BTNode from, object options = null)
        {
            ((UnityEngine.Transform)MyAgent).SetAsLastSibling();
            return Status.Succeeded;
        }
    }
}




