///********************************************************************************************************************************
///The code on this page is generated by the code generator, do not manually modify.
///CodeGenerator: Megumin.CSCodeGenerator.  Version: 1.0.1
///CodeGenericBy: Megumin.AI.BehaviorTree.Editor.NodeGenerator
///CodeGenericSourceFilePath: Packages/com.megumin.ai/Editor/BehaviorTree/Generator/NodeGeneraotr.asset
///********************************************************************************************************************************

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.AI.BehaviorTree
{
    [Icon("d_Transform Icon")]
    [DisplayName("Transform_Rotate")]
    [Category("UnityEngine/Transform")]
    [AddComponentMenu("Rotate(Single, Single, Single)")]
    public sealed class Transform_Rotate_Single_Single_Single_Node : BTActionNode<UnityEngine.Transform>
    {
        [Space]
        public Megumin.Binding.RefVar_Float xAngle;
        public Megumin.Binding.RefVar_Float yAngle;
        public Megumin.Binding.RefVar_Float zAngle;

        protected override Status OnTick(BTNode from, object options = null)
        {
            ((UnityEngine.Transform)MyAgent).Rotate(xAngle, yAngle, zAngle);
            return Status.Succeeded;
        }
    }
}




