///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：$(CodeGenericType)
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [Icon("Transform Icon")]
    [DisplayName("Transform_IsChildOf")]
    [Category("Unity/Transform")]
    [AddComponentMenu("IsChildOf(Transform)")]
    public sealed class Transform_IsChildOf_Transform : ConditionDecorator<UnityEngine.Transform>
    {
        [Space]
        public Megumin.Binding.RefVar_Transform parent;

        public Megumin.Binding.RefVar_Bool Result;

        public override bool CheckCondition(object options = null)
        {
            var result = ((UnityEngine.Transform)MyAgent).IsChildOf(parent);

            if (Result != null)
            {
                Result.Value = result;
            }

            return result;
        }
    }
}




