///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：$(CodeGenericType)
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [Icon("")]
    [DisplayName("Input_GetJoystickNames")]
    [Category("Unity/Input")]
    [AddComponentMenu("GetJoystickNames")]
    public sealed class Input_GetJoystickNames : BTActionNode
    {

        public Megumin.Binding.RefVar_String_Array Result;

        protected override Status OnTick(BTNode from, object options = null)
        {
            var result = UnityEngine.Input.GetJoystickNames();

            if (Result != null)
            {
                Result.Value = result;
            }

            return Status.Succeeded;
        }
    }
}




