///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：$(CodeGenericType)
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [Icon("")]
    [DisplayName("Input_GetKey")]
    [Category("Unity/Input")]
    [AddComponentMenu("GetKey(String)")]
    public sealed class Input_GetKey_String : ConditionDecorator
    {
        [Space]
        public Megumin.Binding.RefVar_String name;

        public Megumin.Binding.RefVar_Bool Result;

        public override bool CheckCondition(object options = null)
        {
            var result = UnityEngine.Input.GetKey(name);

            if (Result != null)
            {
                Result.Value = result;
            }

            return result;
        }
    }
}




