///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：$(CodeGenericType)
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

using System;

namespace Megumin.GameFramework.AI.Serialization
{
    [Serializable]
    public class IntParameterData : GenericParameterData<int> { }

    [Serializable]
    public class FloatParameterData : GenericParameterData<float> { }

    [Serializable]
    public class DoubleParameterData : GenericParameterData<double> { }

    [Serializable]
    public class LongParameterData : GenericParameterData<long> { }

    [Serializable]
    public class StringParameterData : GenericParameterData<string> { }

    [Serializable]
    public class UnityEngineObjectParameterData : GenericParameterData<UnityEngine.Object> { }

}
