///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：$(CodeGenericType)
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [Icon("")]
    [DisplayName("Vector4_MoveTowards")]
    [Category("Unity/Vector4")]
    [AddComponentMenu("MoveTowards(Vector4, Vector4, Single)")]
    public sealed class Vector4_MoveTowards_Vector4_Vector4_Single : BTActionNode
    {
        [Space]
        public Megumin.Binding.RefVar_Vector4 current;
        public Megumin.Binding.RefVar_Vector4 target;
        public Megumin.Binding.RefVar_Float maxDistanceDelta;

        public Megumin.Binding.RefVar_Vector4 Result;

        protected override Status OnTick(BTNode from, object options = null)
        {
            var result = UnityEngine.Vector4.MoveTowards(current, target, maxDistanceDelta);

            if (Result != null)
            {
                Result.Value = result;
            }

            return Status.Succeeded;
        }
    }
}




