///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：$(CodeGenericType)
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [Icon("")]
    [DisplayName("Vector4_Project")]
    [Category("Unity/Vector4")]
    [AddComponentMenu("Project(Vector4, Vector4)")]
    public sealed class Vector4_Project_Vector4_Vector4 : BTActionNode
    {
        [Space]
        public Megumin.Binding.RefVar_Vector4 a;
        public Megumin.Binding.RefVar_Vector4 b;

        public Megumin.Binding.RefVar_Vector4 Result;

        protected override Status OnTick(BTNode from, object options = null)
        {
            var result = UnityEngine.Vector4.Project(a, b);

            if (Result != null)
            {
                Result.Value = result;
            }

            return Status.Succeeded;
        }
    }
}




