///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：$(CodeGenericType)
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [Icon("ParticleSystem Icon")]
    [DisplayName("ParticleSystem_SetCustomParticleData")]
    [Category("Unity/ParticleSystem")]
    [AddComponentMenu("SetCustomParticleData(List`1, ParticleSystemCustomData)")]
    public sealed class ParticleSystem_SetCustomParticleData_List_1_Vector4_ParticleSystemCustomData : BTActionNode<UnityEngine.ParticleSystem>
    {
        [Space]
        public Megumin.Binding.RefVar_Vector4_List customData;
        public Megumin.Binding.RefVar<UnityEngine.ParticleSystemCustomData> streamIndex;

        protected override Status OnTick(BTNode from, object options = null)
        {
            ((UnityEngine.ParticleSystem)MyAgent).SetCustomParticleData(customData, streamIndex);
            return Status.Succeeded;
        }
    }
}




