///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：$(CodeGenericType)
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [Icon("ParticleSystem Icon")]
    [DisplayName("ParticleSystem_GetCustomParticleData")]
    [Category("Unity/ParticleSystem")]
    [AddComponentMenu("GetCustomParticleData(List`1, ParticleSystemCustomData)")]
    public sealed class ParticleSystem_GetCustomParticleData_List_1_Vector4_ParticleSystemCustomData : BTActionNode<UnityEngine.ParticleSystem>
    {
        [Space]
        public Megumin.Binding.RefVar_Vector4_List customData;
        public Megumin.Binding.RefVar<UnityEngine.ParticleSystemCustomData> streamIndex;

        public Megumin.Binding.RefVar_Int Result;

        protected override Status OnTick(BTNode from, object options = null)
        {
            var result = ((UnityEngine.ParticleSystem)MyAgent).GetCustomParticleData(customData, streamIndex);

            if (Result != null)
            {
                Result.Value = result;
            }

            return Status.Succeeded;
        }
    }
}




