///********************************************************************************************************************************
///本页代码由代码生成器生成，请勿手动修改。The code on this page is generated by the code generator, do not manually modify.
///生成器类型：$(CodeGenericType)
///配置源文件：$(CodeGenericSourceFilePath)
///********************************************************************************************************************************

using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.GameFramework.AI.BehaviorTree
{
    [Icon("Animation Icon")]
    [DisplayName("Animation_IsPlaying")]
    [Category("Unity/Animation")]
    [AddComponentMenu("IsPlaying(String)")]
    public sealed class Animation_IsPlaying_String : ConditionDecorator<UnityEngine.Animation>
    {
        [Space]
        public Megumin.Binding.RefVar_String name;

        public Megumin.Binding.RefVar_Bool Result;

        public override bool CheckCondition(object options = null)
        {
            var result = ((UnityEngine.Animation)MyAgent).IsPlaying(name);

            if (Result != null)
            {
                Result.Value = result;
            }

            return result;
        }
    }
}




