///********************************************************************************************************************************
///The code on this page is generated by the code generator, do not manually modify.
///CodeGenerator: Megumin.CSCodeGenerator.  Version: 1.0.1
///CodeGenericBy: Megumin.AI.BehaviorTree.Editor.NodeGenerator
///CodeGenericSourceFilePath: Packages/com.megumin.ai/Editor/BehaviorTree/Generator/NodeGeneraotr.asset
///********************************************************************************************************************************

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;

namespace Megumin.AI.BehaviorTree
{
    [Icon("d_BoxCollider2D Icon")]
    [DisplayName("Set_BoxCollider2D_edgeRadius")]
    [Category("UnityEngine/BoxCollider2D")]
    [AddComponentMenu("Set_edgeRadius")]
    public sealed class BoxCollider2D_edgeRadius_Set_Node : BTActionNode<UnityEngine.BoxCollider2D>
    {
        [Space]
        public Megumin.Binding.RefVar_Float Value;

        protected override Status OnTick(BTNode from, object options = null)
        {
            ((UnityEngine.BoxCollider2D)MyAgent).edgeRadius = Value;
            return Status.Succeeded;
        }

    }
}




